### ISSUE TITLE
lets learn by writing some python programs

### ISSUE THREAD

**Issue by gnurenga** [selvarajsathish/python-training#5]
- [ ] Read about python coding style
      - https://www.python.org/dev/peps/pep-0008/
      - For code and function comments use this document section `comments and docstring`
         https://github.com/google/styleguide/blob/gh-pages/pyguide.md
- [ ] Create a folder `functions` 
- [ ] Write a function to find the types of the passed argument `find_type_arg()`
- [ ] Write a function, which will take two inputs, `sum_of_inputs()`
       - If the inputs are integer it should return sum of two input
       - If the inputs are string it should return concatenated string
       - If the two inputs are different then it should return -1 
       - in main code return -1 should be handled to tell the user that two inputs should be either integer or string.

`Note:`
- Try to follow the coding style in the above functions. 
- Read about functions, conditional statement if
- Read about `type`
- Read about expression, variables
- Python Strongly typed language, read about it.

**Comment by selvarajsathish** [comment]
Algorithm:
Write a function to find the types of the passed argument:
1.Get argument from user. 
2.Find the type of argument and print result.

Write a function, which will take two inputs and returns sum:
1. Get two  input value from user
2. Check if two inputs are same either string or integer 
3. if two inputs are different return -1
4. if two input are either integer or string sum the two input and return the value

**Comment by selvarajsathish** [comment]
Task completed, so closing.
