### ISSUE TITLE
List, strings, dictionary, tuple

### ISSUE THREAD

**Issue by gnurenga** [selvarajsathish/python-training#7]
Read about

- list
- str
- dict
- tuple

Each of the above data type have in built methods. Read also about methods on above data types

**Comment by selvarajsathish** [comment]
List and strings are studied.

 i have doubt in below methods when i tried in interpreter not working, i need your input on this:
>>> st="selva raj k"
>>> st.center(len(st),'a')
'selva raj k'
>>>

>>> str="selva raj"
>>> str.isspace()
False
>>>

**Comment by gnurenga** [comment]
- Read about padding to understand center

- Read about whitespace to understand isspace

**Comment by gnurenga** [comment]
```Python
center(...)
    S.center(width[, fillchar]) -> string

    Return S centered in a string of length width. Padding is
    done using the specified fill character (default is a space)
```
Above the help document for center the width should be greater than the length of the string then you will get your string st centered with padding character. By default padding character is space.

### Suppose you want to add * before and after \# 

```Python
>>> "#".center(3,'*')
'*#*'
>>>

```

### If you want to add * after \# 
``` Python
>>> "#".center(2,'*')
'#*'
>>>
```

## About isspace

```Python

isspace(...)
    S.isspace() -> bool

    Return True if all characters in S are whitespace
    and there is at least one character in S, False otherwise.
```

As per python help document it says if all character in the string is white space then it will return true. If one character present also it will return false.

Suppose you have a string you want to find white spaces in the string.

```Python
>>> for i in "selva test":
...      print i.isspace()
...
False
False
False
False
False
True
False
False
False
False
>>>
```

**Comment by selvarajsathish** [comment]
Thank you ji..Got it

**Comment by selvarajsathish** [comment]
Completed tuple and dictionary.

**Comment by selvarajsathish** [comment]
summary:
==============

List methods:
-------------
>>>
>>> l=[1,2,3,4]
>>> l.append(5)
>>> l
[1, 2, 3, 4, 5]
>>> x=[a,b]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'a' is not defined
>>> x=['a','b']
>>> l.extend(x)
>>> l
[1, 2, 3, 4, 5, 'a', 'b']
>>> l.insert(5,6)
>>> l
[1, 2, 3, 4, 5, 6, 'a', 'b']
>>> l.remove(5)
>>> l
[1, 2, 3, 4, 6, 'a', 'b']
>>>
>>> l.pop(5)
'a'
>>> l
[1, 2, 3, 4, 6, 'b']
>>> l.index('b')
5
>>> l.extend(x)
>>> l
[1, 2, 3, 4, 6, 'b', 'a', 'b']
>>> l.count('b')
2
>>> l
[1, 2, 3, 4, 6, 'b', 'a', 'b']
>>> l.reverse()
>>> l
['b', 'a', 'b', 6, 4, 3, 2, 1]
>>>
>>> l.sort()
>>> l
[1, 2, 3, 4, 6, 'a', 'b', 'b']
>>>
>>> z=l.copy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'list' object has no attribute 'copy'
>>> l
[1, 2, 3, 4, 6, 'a', 'b', 'b']
>>> x=l.copy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'list' object has no attribute 'copy'
>>> AttributeError: 'list' object has no attribute 'copy'

----here i am getting error in copy() method weather we can use this or not.



Tuple methods:
-----------------
>>> t=(1,2,3,4,'a','b',[1,2,])
>>> t.count()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: count() takes exactly one argument (0 given)
>>> t.count(1)
1
>>> t.count(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'a' is not defined
>>> t.count('b')
1
>>> t.index('b')
5
>>> t=(1,2,3,4,'a','b',[1,2,5])
>>> t.index(5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: tuple.index(x): x not in tuple
>>> len(t)
7
>>> all(t)
True
>>> any(t)
True
>>> enumerate(t)
<enumerate object at 0x059A55A8>
>>> max(t)
'b'
>>> min(t)
1
>>>
>>>
>>> sorted(t)
[1, 2, 3, 4, [1, 2, 5], 'a', 'b']
>>>
>>> sum(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'str'
>>>
>>> tuple(t)
(1, 2, 3, 4, 'a', 'b', [1, 2, 5])
>>> sorted(t)
[1, 2, 3, 4, [1, 2, 5], 'a', 'b']
>>> sorted.reverse(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'builtin_function_or_method' object has no attribute 'reverse'
>>>
>>> t
(1, 2, 3, 4, 'a', 'b', [1, 2, 5])
>>> sorted(t)
[1, 2, 3, 4, [1, 2, 5], 'a', 'b']
>>> t
(1, 2, 3, 4, 'a', 'b', [1, 2, 5])
>>> reversed(t)
<reversed object at 0x0593C870>
>>>



Dictionary methods:
----------------------------
>>> person = {'name': 'selva', 'age': 25}
>>> person.get(name)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'name' is not defined
>>> person.get('name')
'selva'
>>>
>>> person.items()
[('age', 25), ('name', 'selva')]
>>>
>>> z.items()
[]
>>> person.keys()
['age', 'name']
>>>
>>> person.popitem()
('age', 25)
>>> person.popitem()
('name', 'selva')
>>>
>>>
>>> person
{}
>>>
>>> person.popitem()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'popitem(): dictionary is empty'
>>>
>>> person.setdefault()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: setdefault expected at least 1 arguments, got 0
>>> person.setdefault('x')
>>> person
{'x': None}
>>>
>>>
>>> person = {'name': 'selva', 'age': 25}
>>>
>>> person
{'age': 25, 'name': 'selva'}
>>>
>>> person.values()
[25, 'selva']
>>>
>>>
>>> person
{'age': 25, 'name': 'selva'}
>>>
>>> person2=person.copy()
>>> person2
{'age': 25, 'name': 'selva'}
>>> person2.pop('age')
25
>>> person2
{'name': 'selva'}
>>> person
{'age': 25, 'name': 'selva'}
>>>
>>> person2.fromkeys('x',y)
{'x': ['r', 'a', 'j']}
>>> x
['a', 'b']
>>> y
['r', 'a', 'j']
>>> person2.pop('x')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'x'
>>> person2
{'name': 'selva'}
>>>
>>>
>>>
>>> person
{'age': 25, 'name': 'selva'}
>>> person.setdefault("salary",25)
25
>>>
>>> person
{'salary': 25, 'age': 25, 'name': 'selva'}
>>>
>>>
>>> person2
{'name': 'selva'}
>>> person2['name']='raj'
>>> person2
{'name': 'raj'}
>>> person.update(person2)
>>> person
{'salary': 25, 'age': 25, 'name': 'raj'}
>>>
>>> person.pop('salary')
25
>>>
>>> person
{'age': 25, 'name': 'raj'}
>>>

**Comment by selvarajsathish** [comment]
above this any important  method i missed please let me know...
string method output not copied here.

**Comment by selvarajsathish** [comment]
String Methods:
===============
>>> str='selvaraj'
>>> str.capitalize()
'Selvaraj'
>>>
>>> str.count()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: count() takes at least 1 argument (0 given)
>>> str.count("a")
2
>>>
>>> str.center(10,"*")
'*selvaraj*'
>>>
>>> str.encode(base64,'strict')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'base64' is not defined
>>> str.encode('base64','strict')
'c2VsdmFyYWo=\n'
>>>
>>> 'c2VsdmFyYWo=\n'.decode('base64','strict')
'selvaraj'
>>>
>>> str.endswith('j')
True
>>> str.endswith('a')
False
>>>
>>> str='selva\traj'
>>>
>>> str.expandtabs(1)
'selva raj'
>>>
>>> str='selvaraj'
>>> str.expandtabs(1)
'selvaraj'
>>>
>>> str.find('a')
4
>>>
>>> str.find('l')
2
>>> str.find('x')
-1
>>>
>>> str.index('a')
4
>>> str.index('l')
2
>>> str.index('x')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: substring not found
>>>
>>> 'my name is {}'.format(str)
'my name is selvaraj'
>>>
>>> str1='kandasamy'
>>> 'my name is {}{}'.format(str,str1)
'my name is selvarajkandasamy'
>>>
>>> str.isalpha()
True
>>>
>>> str.isalnum()
True
>>>
>>> str.isdigit()
False
>>>
>>> str.islower()
True
>>>
>>> str.isupper()
False
>>>
>>> str.isspace()
False
>>>
>>> str.istitle()
False
>>>
>>> ls=list(str)
>>> ls
['s', 'e', 'l', 'v', 'a', 'r', 'a', 'j']
>>> str2=''.join(ls)
>>> str2
'selvaraj'
>>>
>>> str.ljust(10,"x")
'selvarajxx'
>>>
>>> str.rjust(12,"x")
'xxxxselvaraj'
>>>
>>> str.upper()
'SELVARAJ'
>>>
>>> str.lower()
'selvaraj'
>>>
>>> str=' selvaraj '
>>> str.lstrip()
'selvaraj '
>>>
>>> str.rstrip()
' selvaraj'
>>>
>>>
>>>
>>> str=str.strip()
>>>
>>> str
'selvaraj'
>>>
>>> str.partition('a')
('selv', 'a', 'raj')
>>>
>>> str.replace('a','x')
'selvxrxj'
>>>
>>> str.replace('va','x')
'selxraj'
>>>
>>> str.rfind('a')
6
>>> str.rfind('x')
-1
>>> str.rindex('x')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: substring not found
>>>
>>> str.rindex('a')
6
>>>
>>> str.rpartition('a')
('selvar', 'a', 'j')
>>>
>>> str.split()
['selvaraj']
>>> str
'selvaraj'
>>> str="selva raj"
>>> str.split('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: empty separator
>>> str.split(' ')
['selva', 'raj']
>>>
>>> str
'selva raj'
>>> str.startswith('s')
True
>>> str.startswith('a')
False
>>>
>>> str.swapcase()
'SELVA RAJ'
>>>
>>> str.swapcase()
'SELVA RAJ'
>>> str=str.swapcase()
>>> str
'SELVA RAJ'
>>> str.swapcase()
'selva raj'
>>>
>>> str.title()
'Selva Raj'
>>>
>>> str.translate(None,"a")
'SELVA RAJ'
>>> str.translate(None,"A")
'SELV RJ'
>>>
>>> str
'SELVA RAJ'
>>> str.zfill(14)
'00000SELVA RAJ'
>>>

**Comment by selvarajsathish** [comment]
Can you Please assign new task...

**Comment by gnurenga** [comment]
@selvarajsathish For any study task don't paste your try out in comments. It is tough for me to read.
If you want to put your try out directly push to master for any study task. Be more specific about your issues. Also read forum before asking doubts.

**Comment by selvarajsathish** [comment]
ok I will take care in feature.
